name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/requirements.txt'
      - '**/*.spec'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/requirements.txt'
      - '**/*.spec'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: 'Batch Image Converter'
        path: src/dist/windows # or path/to/artifact
